from app import db
from typing import List
import sqlalchemy as sa
import sqlalchemy.orm as so

# NOTE:Tables are automatically generated by FLASK-SQLAlchemy


class User(db.Model):
    id: so.Mapped[int] = so.mapped_column(primary_key=True)
    username: so.Mapped[str] = so.mapped_column(unique=True)
    email: so.Mapped[str]


class Poll(db.Model):
    id: so.Mapped[int] = so.mapped_column(primary_key=True)
    question: so.Mapped[str]
    answers: so.Mapped[List["PollAnswer"]] = so.relationship()


class PollAnswer(db.Model):
    id: so.Mapped[int] = so.mapped_column(primary_key=True)
    answer: so.Mapped[str]
    poll_id: so.Mapped[str] = so.mapped_column(sa.ForeignKey("poll.id"))
