"""Update User class to most recent schema

Revision ID: 2444bacac664
Revises: 4f8bb18bc91f
Create Date: 2024-11-28 19:58:29.293332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2444bacac664'
down_revision = '4f8bb18bc91f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.Enum('male', 'female', 'non_binary', name='gender'), nullable=True))
        batch_op.add_column(sa.Column('continent', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('region', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('account_created', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_active', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_active')
        batch_op.drop_column('account_created')
        batch_op.drop_column('city')
        batch_op.drop_column('region')
        batch_op.drop_column('country')
        batch_op.drop_column('continent')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
