"""Update Poll class to most recent schema. Change relationship syntax.

Revision ID: 445a7c4b688d
Revises: 2444bacac664
Create Date: 2024-11-28 20:39:48.396067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '445a7c4b688d'
down_revision = '2444bacac664'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_poll')
    with op.batch_alter_table('poll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('poll_type', sa.Enum('CHOOSE_ONE', 'CHOOSE_MANY', 'NUMERIC_STAR', 'NUMERIC_SCALE', 'RANKED_POLL', 'TEXT_POLL', 'TIER_LIST', name='polltype'), server_default='CHOOSE_ONE', nullable=False))
        batch_op.add_column(sa.Column('reveals', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('reports', sa.Integer(), server_default='0', nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_poll_user_id_poll'), 'poll', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_column('account_created')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_created', sa.DATETIME(), nullable=True))
        batch_op.drop_column('date_created')

    with op.batch_alter_table('poll', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_poll_user_id_poll'), type_='foreignkey')
        batch_op.drop_column('reports')
        batch_op.drop_column('reveals')
        batch_op.drop_column('poll_type')
        batch_op.drop_column('user_id')

    op.create_table('_alembic_tmp_poll',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('poll_type', sa.VARCHAR(length=13), server_default=sa.text("'CHOOSE_ONE'"), nullable=False),
    sa.Column('reveals', sa.INTEGER(), nullable=False),
    sa.Column('reports', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['poll.id'], name='fk_poll_user_id_poll'),
    sa.PrimaryKeyConstraint('id', name='pk_poll')
    )
    # ### end Alembic commands ###
