"""Remove linkbetween PollAnswer and Response

Revision ID: 793ec6d5be88
Revises: 445a7c4b688d
Create Date: 2024-11-28 21:17:34.499688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '793ec6d5be88'
down_revision = '445a7c4b688d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('poll_answer', schema=None) as batch_op:
        batch_op.alter_column('poll_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('poll_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_index('ix_response_timestamp')
        batch_op.drop_constraint('fk_response_answer_id_poll_answer', type_='foreignkey')
        batch_op.drop_column('answer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_response_answer_id_poll_answer', 'poll_answer', ['answer_id'], ['id'])
        batch_op.create_index('ix_response_timestamp', ['timestamp'], unique=False)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('poll_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('poll_answer', schema=None) as batch_op:
        batch_op.alter_column('poll_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('poll', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
