"""Finish migration to launch schema.

Revision ID: ebf032b816b7
Revises: 793ec6d5be88
Create Date: 2024-11-28 21:39:26.896629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebf032b816b7'
down_revision = '793ec6d5be88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poll', schema=None) as batch_op:
        batch_op.drop_constraint('fk_poll_user_id_poll', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_poll_user_id_user'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poll', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_poll_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_poll_user_id_poll', 'poll', ['user_id'], ['id'])

    # ### end Alembic commands ###
