"""initial migration.

Revision ID: ee92938d9bed
Revises: 
Create Date: 2024-11-21 18:48:02.402195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee92938d9bed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poll_answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer', sa.String(), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')

    with op.batch_alter_table('poll_answer', schema=None) as batch_op:
        batch_op.drop_column('answer')

    # ### end Alembic commands ###
