"""Add response table.

Revision ID: e7ef2ac7be7c
Revises: ee92938d9bed
Create Date: 2024-11-22 10:13:07.630724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7ef2ac7be7c'
down_revision = 'ee92938d9bed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('poll_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('answer_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_response_poll_id_poll'), 'poll', ['poll_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_response_user_id_user'), 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_response_answer_id_poll_answer'), 'poll_answer', ['answer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_response_answer_id_poll_answer'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_response_user_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_response_poll_id_poll'), type_='foreignkey')
        batch_op.drop_column('answer_id')
        batch_op.drop_column('poll_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
